# Generated by Django 5.1 on 2024-09-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voltaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(max_length=50)),
                ('profundidad_descarga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabricante', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ControladorDeCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('corriente_nominal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltaje_entrada_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(max_length=50)),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabricante', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('potencia_maxima', models.DecimalField(decimal_places=2, max_digits=6)),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltaje_entrada_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltaje_entrada_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('salida_ac', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabricante', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PanelSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('potencia', models.DecimalField(decimal_places=2, max_digits=6)),
                ('eficiencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltaje_operacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('corriente_operacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fabricante', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaFotovoltaico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('tipo_sistema', models.CharField(max_length=50)),
                ('consumo_diario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('baterias', models.ManyToManyField(blank=True, to='solar_systems.bateria')),
                ('controladores', models.ManyToManyField(blank=True, to='solar_systems.controladordecarga')),
                ('inversores', models.ManyToManyField(to='solar_systems.inversor')),
                ('paneles', models.ManyToManyField(to='solar_systems.panelsolar')),
            ],
        ),
    ]
